const mongoose=require('mongoose');
// creating my schema
const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        require:true,
        trim:true
    },
    lastName:{
        type:String,
        require:true,
        trim:true
    },
    email:{
        type:String,
        require:true,
        unique:true,
        trim:true
        
    },
    phoneNumber:{
        type:Number,
        require:true,
        unique:true,
        trim:true
    },
    password:{
        type:String,
        require:true,
        trim:true
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    profilePicture:{
        profileUrl:{type:String}
    },
    availableBalance:{
        type:Number,
        trim:true,
        default:0
    },
    totalExpenses:{
        type:Number,
        default:0
    },
    expenseTracker:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"expenses"
    }],
    budgetPlanner:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"budget"
    }],
    debtManager:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"debt"
    }],
    userIncome:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"income"  
    }],
   blacklist:[]
  
},{timestamps:true});
const userModel=mongoose.model('financialMangement',userSchema);
module.exports=userModel